### ISSUE TITLE
Unit tests for class box

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team2#13]

**Comment by nerya50** [comment]
@addirabasker, please check this issue and reclose it.

**Comment by addirabasker** [comment]
@nerya50 
first of all - great coverage!
secondly here are my two pointers:
1. try to minimize the amount of assert lines per test function:
![image](https://user-images.githubusercontent.com/33811361/48660214-ebe4bc00-ea66-11e8-856c-46692aa7a13b.png)
test like these can be split to two different test functions.
2. import azzert and use it's methods instead of assert - for example change assertEquals(X,Y) to azzert.assertEquals(X,Y)

**Comment by addirabasker** [comment]
great
