### ISSUE TITLE
Choose technology: Web / Android

### ISSUE THREAD

**Issue by DorKab** [TechnionYP5779/team2#159]

**Comment by addirabasker** [comment]
first of all both can be a great option for development... but we, as a team, need to prioritize one over the other so we need to ask ourselves which should we focus on?
I hope this answer will be as informational as can be and to do so here is a list of pros and cons for each of them:

web technology:
	designwise there are plenty of options for creating a website such as wix.com, GoDaddy and web.com
	* HTML 
	* CSS
	* JavaScript
	* Bootstrap , Angular.js and React.js - this is for frontend
	* PHP or Node.js - this is for backend
	* AWS such as digitalOcean, Amazon EC2, AWS Fargate etc - these are cloud services for deployment, managing and scaling more efficiently
	* we can utilize eclipse for the job with WTP plugin.

android technology:
	* android studio - but as said in this yearly project we should mostly rely on eclipse while this option relys on the IntelliJ IDE
	* xml

web - pros:
	* anyone who has access to the internet can access the website - both android and IOS users.
	* can fit both on mobile and pc(but why should we even consider pc...)
	* it is time consuming but since there are a lot of components here and the fact that we are a team of 7 people mean the it can be split to smaller
		chunks which we can handle.

web - cons:
	* a bit more difficult since theres a frontend, backend, MEAN and MERN developer

android - pros:

android - cons:
	* requires other IDEs such as IntelliJ and android studio
	* missing IOS users
	* learning

**Comment by GuySuday** [comment]
## Android technology:
* android studio - but as said in this yearly project we should mostly rely on eclipse while this option relys on the IntelliJ IDE
* xml

### pros:
* way more convenient as an app than a web service 
* half of the team have prior knowledge from the last year
* convenient IDE to work with 
* visually impressive from the start
* more suitable - parking app is more usable from website while using in the car
* support offline mode

### cons:
* requires other IDEs such as IntelliJ and android studio
* missing IOS users
* learning time in android is greather than in web beacuse each team member has to learn it rather than just a part of what we need in web dev...
* some people does have an android phone

**Comment by talporat** [comment]
## web technology:
designwise there are plenty of options for creating a website such as wix.com, GoDaddy and web.com
* HTML
* CSS
* JavaScript
* Bootstrap , Angular.js and React.js - this is for frontend
* PHP or Node.js - this is for backend
* AWS such as digitalOcean, Amazon EC2, AWS Fargate etc - these are cloud services for deployment, managing and scaling more efficiently
* we can utilize eclipse for the job with WTP plugin.

### pros:
* anyone who has access to the internet can access the website - both android and IOS users.
* can fit both on mobile and pc(but why should we even consider pc...)
* it is time consuming but since there are a lot of components here and the fact that we are a team of 7 people mean the it can be split to smaller
chunks which we can handle.
* other teams implemented in web, and it looks simple

### cons:
* a bit more difficult since theres a frontend, backend, MEAN and MERN developer
* half of the team have basic prior knowledge from high school
* looks primitive without proper styling skills
* requires access to the website while driving
* requires internet access

**Comment by GuySuday** [comment]
## conclusions
### App
* app team - Guy, Tal, Addir
* other teams - 4
### Web
* web team - Dor, Omer, Jessica, Nerya
* other teams - 1,3
