### ISSUE TITLE
Unit tests for interface is

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team2#25]

**Comment by nerya50** [comment]
@addirabasker , please check this issue and reclose it.

**Comment by addirabasker** [comment]
@nerya50 
first of all - great coverage!
secondly here are my two pointers:
1. minimize the amount of assert lines per test function:
![image](https://user-images.githubusercontent.com/33811361/48660280-01a6b100-ea68-11e8-9586-a89c3c5ed8a3.png)
here you can clearly see that you can split this test to 6 different tests.
2. import box and use it instead of (Some Class).valueOf - 
![image](https://user-images.githubusercontent.com/33811361/48660291-387cc700-ea68-11e8-9d42-8e9979888947.png)

**Comment by nerya50** [comment]
@addirabasker please recheck it

**Comment by addirabasker** [comment]
great
